# Site settings
title: TanSAARnia
email: info@tansaarnia.com
description: >
  Here you can donate and support our project
# this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username: 
github_username: 

domain: "https://www.tansaarnia.com"

# Build settings
markdown: kramdown

counter_get: https://api.countapi.xyz/get/tansaarnia.com/donations
counter_hit: https://api.countapi.xyz/hit/tansaarnia.com/donations